/*
* _.js
* @copyright: sinan eker, selsyourself@gmail.com
* @license:
* * * Licensed under the Apache License, Version 2.0
* * * http://www.apache.org/licenses/LICENSE-2.0
*/
var _=function(){var a={__proto__:null,jQuery:window.jQuery},b=new Class({}),c={__proto__:null};Class.Mutators.setJquery=function(d){if(d)return this.prototype.setOptions({jQuery:a.jQuery})};Class.Mutators.baseStore=function(a){return this.prototype.setOptions({baseStore:a})};Class.Mutators.jQuery=function(d){var b=this;a.jQuery.fn[d]=function(c){var h=Array.prototype.slice.call(arguments,1);if("string"==typeOf(c)){var e=a.jQuery(this).data(d);e&&e[c].apply(e,h)}else a.jQuery(this).data(d,new b(this.selector,
a.jQuery.extend(b.prototype.options,c)))}};b.AjaxCallbacks=new Class({options:{success:function(a){return c.ajaxSuccessResponse=a}},initialize:function(){return this.options}});b.Factory=new Class({Implements:[Options],baseStore:c,initialize:function(){this.last="";this.res=[];return this},store:function(a,b){this.last=b;return this.res[b]=a},clear:function(){this.res=void 0;this.res=[]},getLast:function(){return void 0!==this.res[this.last]?this.res[this.last]:{__proto__:null}},get:function(a){return void 0!==
this.res[a]?this.res[a]:{__proto__:null}}});b.Maker=new Class({Extends:b.Factory,initialize:function(a,c){this.parent(a);var g=new b.AjaxCallbacks;a.extend(g,c);this.store(a.ajax(g),"Maker");return this},lastRequest:function(){return this.res.Maker}});return new Class({Extends:b.Factory,jQuery:"hybrid",options:{jq:a.jQuery},initialize:function(a,b,c){a=a||void 0;b=b||void 0;this.setOptions(c);this.jQuery=this.options.jq;this.parent(this.jQuery);return"function"==typeOf(b)?(a=void 0!==a?this.jQuery(a):
void 0,this.store(b.apply(this,[a,this.jQuery]),"initialize")):void 0!==a&&void 0!==b?this.store(this.jQuery(a,b),"initialize"):!a?this:this.store(this.jQuery(a),"initialize")},$:function(a){return this.store(!a?[]:this.jQuery(a),"$")},ajax:function(a){a=a||{};var c=new b.Maker(this.jQuery,a);a=c.lastRequest();c.clear();return a}})}();window._=_;window.hybrid=window._;
var _b=function(){_.DatepickerInit=new Class({source:"https://raw.github.com/eternicode/bootstrap-datepicker/master/js/bootstrap-datepicker.js",initialize:function(a){return void 0==a?[]:a.getScript(this.source).fail(function(){console.log("Unable to load the datepicker plugin.")})}});_.StringValidation=new Class({initialize:function(){return this},stringCollection:function(a,b){var c=!1;if("array"!==typeOf(a))return!1;"string"==typeOf(b)?(c=a.map(function(a){return a==b}).filter(function(a){return!0==
a}),void 0!==c[0]&&(c=!0)):"object"==typeOf(b)?c=a.map(function(a){return void 0!==b[a]}).filter(function(a){return!0==a}).every(function(a){return!1!==a}):(a=a.flatten(),a==b&&(c=!0));return c}});return new Class({Extends:_,jQuery:"bhybrid",initialize:function(a){this.parent(a);return this},modal:function(a){a=a||void 0;if(void 0==a)return this.store(this.get("initialize").modal(),"modal");var b=new _.StringValidation;return b.stringCollection(["toggle","show","hide"],a)||b.stringCollection(["backdrop",
"keyboard","show","remote"],a)?this.store(this.get("initialize").modal(a),"modal"):[]},tooltip:function(a){a=a||void 0;if(void 0==a)return this.store(this.get("initialize").tooltip(),"tooltip");var b=new _.StringValidation;return b.stringCollection(["toggle","show","hide","destroy"],a)||b.stringCollection("animation html placement selector title trigger delay container".split(" "),a)?this.store(this.get("initialize").tooltip(a),"tooltip"):[]},popover:function(a){a=a||void 0;if(void 0==a)return this.store(this.get("initialize").popover(),
"popover");var b=new _.StringValidation;return b.stringCollection(["toggle","show","hide","destroy"],a)||b.stringCollection("animation html placement selector trigger title content delay container".split(" "),a)?this.store(this.get("initialize").popover(a),"popover"):[]},datepicker:function(a){a=a||void 0;var b=this.get("initialize");if(void 0==this.jQuery.fn.datepicker)return new _.DatepickerInit(this.jQuery);var c=new _.StringValidation;return"object"==typeOf(a)&&void 0!==a.setValue?this.store(b.datepicker("setValue",
a.setValue),"datepicker"):void 0==a?this.store(b.datepicker(),"datepicker"):c.stringCollection(["show","hide","place"],a)||c.stringCollection(["format","weekStart","viewMode","minViewMode"],a)?this.store(b.datepicker(a),"datepicker"):[]}})}();window._b=_b;window.bhybrid=window._b;
var _r=function(){return new Class({Extends:_,jQuery:"rhybrid",setJquery:!0,Implements:[Options],source:"http://requirejs.org/docs/release/2.1.5/minified/require.js",options:{fail:function(){console.log("Unable to load require.js");return!1}},initialize:function(a,b,c,d){a=a||void 0;b=b||void 0;c=c||void 0;this.setOptions(d||void 0);this.parent(document);this.ready=!0;try{throw require;}catch(f){"object"==typeOf(f)&&"require is not defined"==f.message&&(this.ready=!1)}return!this.ready?this.jQuery.getScript(this.source).fail(this.options.fail):
require.apply(this,[a,b,c])}})}();window._r=_r;window.rhybrid=window._r;
